# Generated by Django 6.0.3 on 2026-03-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_course_owner_lesson_owner"),
        ("users", "0002_subscriptions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscriptions",
            new_name="Subscription",
        ),
    ]
