# Generated by Django 6.0.3 on 2026-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=500,
                null=True,
                verbose_name="Сссылка на оплау",
            ),
        ),
    ]
