# Generated by Django 6.0.3 on 2026-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="link",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="session_id",
        ),
        migrations.AddField(
            model_name="payments",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Price ID"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Product ID"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Session ID"
            ),
        ),
    ]
