# Generated by Django 6.0.3 on 2026-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payments_link_remove_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("card", "Банковская карта"),
                ],
                default="cash",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
