"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Локально читаем .env, в Docker переменные уже загружены через env_file
if not os.path.exists("/.dockerenv"):
    load_dotenv(".env", override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Путь к корню проекта (где лежит manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Разрешенные хосты
# Какие домены/IP могут обращаться к сайту
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # --- Стандартные приложения Django ---
    "django.contrib.admin",  # Админ-панель (yourdomain.ru/admin/)
    "django.contrib.auth",  # Пользователи, группы, права доступа
    "django.contrib.contenttypes",  # Связи между моделями (служебное)
    "django.contrib.sessions",  # Хранение сессий пользователей
    "django.contrib.messages",  # Всплывающие сообщения (успех, ошибка)
    "django.contrib.staticfiles",  # Работа со статикой (CSS, JS, картинки)
    # --- Сторонние библиотеки ---
    "rest_framework",  # Django REST Framework — создание API
    "rest_framework_simplejwt",  # JWT-токены для безопасной авторизации через API
    "corsheaders",  # Разрешает запросы к API с других доменов (нужно для фронтенда)
    "django_filters",  # Фильтрация данных в API (поиск, сортировка)
    "drf_spectacular",  # Современная автодокументация API (OpenAPI 3.0)
    "django_celery_beat",  # Планировщик задач Celery (периодические задачи)
    # --- Приложения проекта ---
    "users",  # Пользователи (кастомная модель User)
    "lms",  # Learning Management System (курсы, уроки)
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),  # Имя нашей базы
        "USER": os.getenv("DB_USER"),  # Имя пользователя PostgreSQL
        "PASSWORD": os.getenv("DB_PASSWORD"),  # Пароль пользователя PostgreSQL
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # Нельзя использовать логин/email как часть пароля
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # Минимальная длина пароля (по умолчанию 8 символов)
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        # Запрещает популярные пароли (qwerty, 123456, password)
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        # Запрещает пароли, состоящие только из цифр (12345678)
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Язык интерфейса (кнопки, надписи в админке)
LANGUAGE_CODE = "en-us"

# Часовой пояс (влияет на auto_now_add, даты в админке)
TIME_ZONE = "Europe/Moscow"

# Интернационализация (переводы на другие языки)
USE_I18N = True

# Использовать часовые пояса (хранить время в UTC, показывать в локальном)
USE_TZ = True

# СТАТИЧЕСКИЕ И МЕДИА ФАЙЛЫ

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL для доступа к статике (CSS, JS, картинки сайта)
STATIC_URL = "static/"

# Папка, куда collectstatic собирает ВСЮ статику для продакшена
# После деплоя запустить: python manage.py collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# URL для доступа к медиа-файлам (загруженные пользователем файлы)
# В браузере: yourdomain.ru/media/uploads/photo.jpg
MEDIA_URL = "media/"

# Папка, где хранятся загруженные пользователями файлы
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ТИП ПОЛЯ ПО УМОЛЧАНИЮ ДЛЯ ПЕРВИЧНЫХ КЛЮЧЕЙ
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# КАСТОМНАЯ МОДЕЛЬ ПОЛЬЗОВАТЕЛЯ

# Вместо стандартной модели User используется своя (users.User)
# Позволяет добавить свои поля (телефон, аватар, дата рождения)
AUTH_USER_MODEL = "users.User"

# НАСТРОЙКИ DJANGO REST FRAMEWORK (API)

REST_FRAMEWORK = {
    # Фильтрация по умолчанию (поиск и сортировка в API)
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    # Способ аутентификации через JWT-токены (вместо сессий/куки)
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Доступ по умолчанию: только авторизованные пользователи
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Генератор OpenAPI-схемы для автодокументации
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

#  НАСТРОЙКИ JWT-ТОКЕНОВ

SIMPLE_JWT = {
    # Access-токен — короткоживущий ключ доступа
    # 5 минут для безопасности: если украдут — быстро истечёт
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    # Refresh-токен — долгоживущий токен обновлени
    # Нужен, чтобы получить новый access-токен без повторного ввода пароля
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# CORS_ALLOWED_ORIGINS = [
#     "https://read-only.example.com",
#     "https://read-and-write.example.com",
# ]
#
# CSRF_TRUSTED_ORIGINS = [
#     "https://read-and-write.example.com",
# ]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # Замените на адрес вашего фронтенд-сервера
]

CSRF_TRUSTED_ORIGINS = [
    "https://read-and-write.example.com",  # Замените на адрес вашего фронтенд-сервера
    # и добавьте адрес бэкенд-сервера
]

# Запрет запросов отовсюду (разрешены только из списка выше)
CORS_ALLOW_ALL_ORIGINS = False


# НАСТРОЙКИ ДОКУМЕНТАЦИИ API (Swagger/OpenAPI)

SPECTACULAR_SETTINGS = {
    "TITLE": "LMS API",  # Название API
    "DESCRIPTION": "API для управления курсами, уроками, подписками и платежами",  # Описание
    "VERSION": "1.0.0",  # Версия API
    "SERVE_INCLUDE_SCHEMA": False,  # Не показывать схему в ответах API
}

# НАСТРОЙКИ STRIPE (ПЛАТЕЖНАЯ СИСТЕМА)

# Ключи от Stripe(для подключения платежей)
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY")

# Маршрут перехода при успешной оплаты
STRIPE_SUCCESS_URL = os.getenv("STRIPE_SUCCESS_URL")
# Маршрут перехода при отмене оплаты
STRIPE_CANCEL_URL = os.getenv("STRIPE_CANCEL_URL")

# Настройки Redis
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB = os.getenv("REDIS_DB")


# Настройка Celery
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CELERY_TIMEZONE = TIME_ZONE
# Записывает в лог, когда начата задача
CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Настройка расписания задачи
CELERY_BEAT_SCHEDULE = {
    "block-inactive-users-daily": {
        "task": "users.tasks.block_inactive_users",  # The name of the task
        "schedule": crontab(
            hour=0, minute=0
        ),  # каждый день в полночь  # How often the task should run
    },
    # Add more tasks as needed
}

# Настройка отправки писем
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL")

SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
