# Generated by Django 6.0.3 on 2026-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_alter_course_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Цена курса в рублях", verbose_name="Цена курса"
            ),
        ),
    ]
