# Generated by Django 6.0.3 on 2026-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Цена в рублях (если урок продаётся отдельно)",
                null=True,
                verbose_name="Цена урока",
            ),
        ),
    ]
