# Generated by Django 6.0.3 on 2026-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
